# Generated by Django 5.2.8 on 2025-11-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='contraportada',
            field=models.TextField(blank=True, help_text='Descripción detallada del libro para la contraportada', null=True),
        ),
    ]
